[package]
name = "pbloom"
version = "0.1.2"
edition = "2021"
description = "A portable bloom filter implementation in Rust"
license = "MIT"

[dependencies]
murmur3 = "0.5.2"
rmp = "0.8.14"

[dev-dependencies]
hex = "0.4.3"
hex-literal = "0.4.1"
sha2 = "0.10.8"
