name: docker image

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ${{ matrix.builder }}

    strategy:
      matrix:
        include:
          - builder: buildjet-8vcpu-ubuntu-2204
            platform: amd64
          - builder: buildjet-8vcpu-ubuntu-2204-arm
            platform: arm64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: true
          provenance: false
          platforms: linux/${{ matrix.platform }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/pbloom:${{ github.ref_name }}-${{ matrix.platform }}
            ghcr.io/${{ github.repository_owner }}/pbloom:latest-${{ matrix.platform }}

  manifest:
    runs-on: buildjet-8vcpu-ubuntu-2204
    needs: release

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tag manifest and push
        run: |
          docker manifest create \
            ghcr.io/${{ github.repository_owner }}/pbloom:${{ github.ref_name }} \
            --amend ghcr.io/${{ github.repository_owner }}/pbloom:${{ github.ref_name }}-amd64 \
            --amend ghcr.io/${{ github.repository_owner }}/pbloom:${{ github.ref_name }}-arm64
          docker manifest push ghcr.io/${{ github.repository_owner }}/pbloom:${{ github.ref_name }}

      - name: Create latest manifest and push
        run: |
          docker manifest create \
            ghcr.io/${{ github.repository_owner }}/pbloom:latest \
            --amend ghcr.io/${{ github.repository_owner }}/pbloom:latest-amd64 \
            --amend ghcr.io/${{ github.repository_owner }}/pbloom:latest-arm64
          docker manifest push ghcr.io/${{ github.repository_owner }}/pbloom:latest
